Remove copy of iprange
malfunkt/arpfox pull request #4
Opened 2016-10-29 19:32 UTC by xiam

Hey @ArturoVM, this PR removes the local `iprange` copy and uses the new import path. Could you give it a look?

2016-10-30 23:55 UTC, ArturoVM commented
Sure!

2016-10-30 23:57 UTC, arturovm requested changes
Looks good to me, except for that one unnecessary step!

2016-10-30 23:57 UTC, ArturoVM commented on Makefile
>  generate:
This generate step is no longer necessary, since the `iprange` repo has the latest generated code.

2016-10-31 03:08 UTC, ArturoVM commented
Hey @xiam, I removed that generate step, but I don't have push access to this repo, I think.

2016-10-31 12:48 UTC, xiam commented
> Hey @xiam, I removed that generate step, but I don't have push access to this repo, I think.

Oops, no. Sorry, fixed now.

2016-10-31 16:19 UTC, arturovm approved these changes

2016-10-31 16:20 UTC, merged